name: PushCar
main: com.ibs.oldman.pushcar.Main
version: ${project.version}
api-version: 1.13
author: Yezi
commands:
  pc:
    description: Command of PC plugin
    useage: /pc [subcommand]
    aliases: "pushcar"